name: MasterDeployCI
on:
  push:
    branches:
    - main
    
jobs:
  build:    
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: CreateReleaseFolder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release

    - name: BuildArtifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: OnePlus6Oxygen_22.J.62_debloat
        path: ./release

    - name: UploadArtifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.upload-artifact.outputs.upload_url }}
        asset_path: OnePlus6Oxygen_22.J.62_debloat.zip
        asset_name: OnePlus6Oxygen_22.J.62_debloat.zip
        asset_content_type: application/zip

    - name: BumpVersion_PushTag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: keithweaver
