name: MasterDeployCI
on:
  push:
    branches:
    - main
    - release/*
    
jobs:
  zip:
    name: generate zip file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r OnePlus6Oxygen_22.J.62_debloat.zip .
    - name: Release to Github
      run: echo "Release"
