name: MasterDeployCI
on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: generate zip file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Zip Folder
      run: zip -r OnePlus6Oxygen_22.J.62_debloat.zip ./release -x ".git/*" ".github/*"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: OnePlus6Oxygen_22.J.62_debloat.zip
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: keithweaver
