name: Build Module

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Upload Asset
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Id
        id: mId
        run: echo "::set-output name=id::$(grep "^id=" module.prop|cut -d'=' -f2)"
        
      - name: Get Version
        id: mVersion
        run: echo "::set-output name=version::$(grep "^version=" module.prop|cut -d'=' -f2)"

      - name: Build Full Version
        run: zip -r "${{ steps.mId.outputs.id }}.full.v${{ steps.mVersion.outputs.version }}.zip" . -x "README.md" ".git/*" ".github/*" 

      - name: Build Light Version
        run: zip -r "${{ steps.mId.outputs.id }}.light.v${{ steps.mVersion.outputs.version }}.zip" . -x "README.md" ".git/*" ".github/*" "/system/app/com.aurora.store/*" "/system/priv-app/CalendarProvider/*" "/system/priv-app/DiracAudioControlService/*" "/system/priv-app/DiracManager/*" "/system/priv-app/OnePlusCamera/*" "/system/priv-app/OnePlusCameraService/*" "/system/product/app/GoogleContactsSyncAdapter/*" "/system/product/app/WebViewGoogle/*" "/system/product/priv-app/GmsCore/*" "/system/product/priv-app/Phonesky/*" "/system/system_ext/app/DynamicDDSService/*" "/system/system_ext/app/OPFilemanager/*" "/system/system_ext/priv-app/Dialer/*" "/system/system_ext/priv-app/OPContacts/*" "/system/system_ext/priv-app/OPMms/" 

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.mVersion.outputs.version }}

      - name: Upload Release Asset Full
        id: upload-release-full
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./${{ steps.mId.outputs.id }}.full.v${{ steps.mVersion.outputs.version }}.zip
          asset_name: ${{ steps.mId.outputs.id }}.full.v${{ steps.mVersion.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Light
        id: upload-release-light
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./${{ steps.mId.outputs.id }}.light.v${{ steps.mVersion.outputs.version }}.zip
          asset_name: ${{ steps.mId.outputs.id }}.light.v${{ steps.mVersion.outputs.version }}.zip
          asset_content_type: application/zip
