name: MasterDeployCI
on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: generate zip file
    runs-on: ubuntu-latest
    steps:
    - name: Zip Folder
      run: zip -r OnePlus6Oxygen_22.J.62_debloat.zip . -x ".git/*" ".github/*"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: OnePlus6Oxygen_22.J.62_debloat.zip
